stages:
  prepare_supabase_predictions_table:
    cmd: python3 src/prepare_supabase_predictions_table.py
    deps:
      - src/prepare_supabase_predictions_table.py
      - supabase_logger.py
    outs:
      - reports/supabase_predictions_table_ready.txt

  ingest:
    cmd: python3 src/ingestion.py
    outs:
      - data/raw/wine_quality.csv

  preprocess:
    cmd: python3 src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/raw/wine_quality.csv
    outs:
      - data/processed/wine_processed.parquet

  prepare:
    cmd: python3 src/prepare_data.py
    deps:
      - src/prepare_data.py
      - data/processed/wine_processed.parquet
    outs:
      - data/processed/splits/train.parquet
      - data/processed/splits/val.parquet
      - data/processed/splits/test.parquet
      - models/preprocessors/preprocessor.joblib

  train:
    cmd: python3 src/train.py
    deps:
      - src/train.py
      - data/processed/splits/train.parquet
      - data/processed/splits/val.parquet
    outs:
      - models/trained/SMOTE_logistic_regression.joblib
      - models/trained/SMOTE_random_forest.joblib
      - models/trained/SMOTE_knn.joblib
      - models/trained/SMOTE_svm.joblib
      - models/trained/SMOTE_xgboost.joblib
      - models/trained/SMOTE_mlp.joblib
      - models/trained/Tomek_logistic_regression.joblib
      - models/trained/Tomek_random_forest.joblib
      - models/trained/Tomek_knn.joblib
      - models/trained/Tomek_svm.joblib
      - models/trained/Tomek_xgboost.joblib
      - models/trained/Tomek_mlp.joblib
      - models/best_model.pkl
      - reports/training_report.json

  evaluate:
    cmd: python3 src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed/splits/test.parquet
      - models/trained/SMOTE_logistic_regression.joblib
      - models/trained/SMOTE_random_forest.joblib
      - models/trained/SMOTE_knn.joblib
      - models/trained/SMOTE_svm.joblib
      - models/trained/SMOTE_xgboost.joblib
      - models/trained/SMOTE_mlp.joblib
      - models/trained/Tomek_logistic_regression.joblib
      - models/trained/Tomek_random_forest.joblib
      - models/trained/Tomek_knn.joblib
      - models/trained/Tomek_svm.joblib
      - models/trained/Tomek_xgboost.joblib
      - models/trained/Tomek_mlp.joblib
    outs:
      - reports/evaluation_report.json
    plots:
      - reports/confusion_matrix_*.png:
          template: confusion
      - reports/roc_curve_*.png:
          template: linear
